name: Serenity Eco Villages
permalink: /blog/:title/
phone: (435) 610-1067
email: serenityechovillages@gmail.com
collections:
  main-pages:
    output: true
  events:
    output: true
  facilitators:
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      _hide_content: false
      permalink: /blog/:title/
      navclass: /blog/    