name: Essence Being Center
permalink: /blog/:title/
collections:
  main-pages:
    output: true
  events:
    output: true
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      _hide_content: false
      permalink: /blog/:title/
      navclass: /blog/    